import { useState } from "react";
import "./App.css";
import fechado from "./assets/biscoito.png";
import aberto from "./assets/aberto.png";
import music from "./assets/biscoitoSound.mp3";

function App() {
  const frasesBiscoito = [
    "Grandes mudanças começam com pequenos passos.",
    "O sucesso vem para quem não desiste.",
    "Acredite em você e tudo será possível.",
    "A paciência é a chave para a sabedoria.",
    "O que você planta hoje, colhe amanhã.",
    "Nunca é tarde para ser quem você quer ser.",
    "A sorte favorece os corajosos.",
    "Uma jornada de mil milhas começa com um único passo.",
    "Aprenda com o passado, viva o presente, sonhe com o futuro.",
    "Seu maior tesouro é o tempo. Use-o bem.",
    "As oportunidades surgem para quem está preparado.",
    "Seja a mudança que você quer ver no mundo.",
    "O que parece difícil hoje será sua vitória amanhã.",
    "Boas energias atraem coisas boas.",
    "O otimismo é o ímã da felicidade.",
    "Cada novo dia é uma nova chance para ser feliz.",
    "Acredite no seu potencial e vá além.",
    "O esforço de hoje é a recompensa de amanhã.",
    "Pense positivo e coisas boas acontecerão.",
    "Nada é impossível para quem tem determinação.",
    "Siga em frente, um passo de cada vez.",
    "O segredo do sucesso está na perseverança.",
    "As dificuldades preparam pessoas comuns para destinos extraordinários.",
    "Você é mais forte do que imagina.",
    "O universo conspira a favor de quem acredita.",
    "Um sorriso pode mudar o seu dia e o de alguém.",
    "A sorte é o encontro da preparação com a oportunidade.",
    "Não tenha medo de errar, pois é errando que se aprende.",
    "A felicidade não é um destino, mas uma forma de viajar.",
    "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
    "Seja gentil e o mundo será gentil com você.",
    "A vida recompensa aqueles que não têm medo de vivê-la.",
    "A melhor maneira de prever o futuro é criá-lo.",
    "A esperança é o ingrediente secreto para grandes conquistas.",
    "A cada dia há uma nova chance de recomeçar.",
    "O tempo é agora, faça acontecer.",
    "O bem que você faz retorna para você.",
    "A confiança é a base de todas as conquistas.",
    "O segredo da felicidade está em aproveitar o momento presente.",
    "Nunca deixe para amanhã o que pode ser feito hoje.",
    "Tudo o que você precisa já está dentro de você.",
    "O amor e a gratidão transformam qualquer situação.",
    "A luz que você procura está dentro de você.",
    "O caminho para o sucesso é dar um passo de cada vez.",
    "Você atrai o que transmite, então espalhe boas vibrações.",
    "Cada dia é uma nova oportunidade para crescer.",
    "A persistência é a ponte entre o sonho e a realização.",
    "Seu destino está em suas mãos, escolha com sabedoria.",
    "O medo é apenas uma ilusão, siga em frente com coragem.",
    "Os desafios são oportunidades disfarçadas.",
    "Pequenas alegrias constroem grandes felicidades.",
    "A vida é um presente, aproveite cada instante.",
    "Confie no seu instinto, ele sabe o caminho.",
    "Você é capaz de realizar coisas incríveis.",
    "O universo tem planos maravilhosos para você.",
    "Nunca subestime o poder de um simples sorriso.",
    "Seja a luz que ilumina o caminho dos outros.",
    "Transforme dificuldades em aprendizados.",
    "A verdadeira riqueza está nas experiências vividas.",
    "Não espere, comece agora.",
    "Seu coração sabe a resposta.",
    "Não compare seu capítulo 1 com o capítulo 20 de alguém.",
    "Grandes sonhos começam com pequenas ações.",
    "A coragem leva você a lugares inesperados.",
    "Toda tempestade passa, o sol sempre volta a brilhar.",
    "Seu potencial é maior do que imagina.",
    "Acredite: você nasceu para vencer.",
    "O amor próprio é o começo de tudo.",
    "Cada dia é uma nova chance para mudar sua vida.",
    "Aprenda a se perdoar e siga em frente.",
    "Não há erros, apenas aprendizados.",
    "A magia acontece fora da zona de conforto.",
    "Você é uma obra-prima em construção.",
    "A força está na sua mente.",
    "Desafios são trampolins para o sucesso.",
    "Seu brilho ninguém pode apagar.",
    "Acredite na sua capacidade de fazer a diferença.",
    "Nada é mais valioso do que a paz interior.",
    "O mundo precisa do seu talento.",
    "Tenha fé no processo.",
    "A mente positiva atrai coisas positivas.",
    "Sonhe alto, o céu é o limite.",
    "Cada obstáculo superado te torna mais forte.",
    "Seu esforço hoje será seu orgulho amanhã.",
    "Boas coisas acontecem para quem tem paciência.",
    "Seja sua própria inspiração.",
    "Respire fundo e continue avançando.",
    "Seja gentil, a vida retribui.",
    "O tempo cura, ensina e fortalece.",
    "Nada pode parar quem tem determinação.",
    "A chave do sucesso é nunca parar de aprender.",
    "Foque no que te faz feliz.",
    "Você tem o poder de mudar sua realidade.",
    "Faça do seu dia algo extraordinário.",
    "Sua história ainda está sendo escrita.",
    "Mantenha o foco, sua vitória está próxima.",
    "Não tenha medo de recomeçar.",
    "Cada pessoa que cruza seu caminho tem algo a ensinar.",
    "O mundo muda quando você muda.",
    "Siga seu coração, mas leve o cérebro junto.",
    "A felicidade está dentro de você.",
    "Grandes coisas acontecem para quem não desiste.",
    "A única pessoa que pode te impedir de crescer é você mesmo.",
    "Acreditar é o primeiro passo para conquistar.",
    "Cultive gratidão e verá milagres acontecerem.",
    "Não tenha medo de ser diferente.",
    "Viva intensamente cada momento.",
    "O que você faz hoje define seu amanhã.",
    "Nada acontece por acaso.",
    "Plante boas sementes e colha bons frutos.",
    "Seu sorriso ilumina o mundo.",
    "A sua jornada é única, aproveite-a.",
    "Desafios são convites para crescer.",
    "O impossível é apenas uma opinião.",
    "Você está exatamente onde precisa estar.",
    "A vida te dá oportunidades todos os dias.",
    "Mude seus pensamentos e mudará sua vida.",
    "Você é mais incrível do que imagina.",
    "Nada pode te impedir, a não ser você mesmo.",
    "A vida começa onde o medo termina.",
    "Você merece tudo o que há de melhor.",
    "Acredite, o melhor ainda está por vir!",
    "Seja paciente, seu tempo chegará.",
    "O segredo da vida é nunca desistir.",
    "A felicidade começa dentro de você.",
    "Tudo tem um propósito, confie no caminho.",
    "O seu brilho ninguém pode apagar.",
    "A vida recompensa os persistentes.",
    "Seja hoje a pessoa que deseja ser amanhã.",
    "Não se limite, vá além!",
    "Nem todos os sonhos se realizam, e tudo bem.",
    "A vida pode ser dura, mas siga em frente.",
    "O tempo não cura tudo, apenas nos ensina a lidar.",
    "Às vezes, você perde sem motivo aparente.",
    "Nem todas as dores têm solução.",
    "Não podemos controlar tudo o que acontece.",
    "Fracassos fazem parte da jornada.",
    "A vida nem sempre é justa.",
    "O esforço nem sempre é recompensado.",
    "As pessoas nem sempre são confiáveis.",
    "Às vezes, desistir é a única opção.",
    "Mesmo dando o seu melhor, pode não ser suficiente.",
    "A felicidade pode ser passageira.",
    "Erros são inevitáveis e podem custar caro.",
    "O tempo não para para ninguém.",
    "Nem sempre há um recomeço.",
    "Algumas oportunidades nunca voltam.",
    "Perdas fazem parte da vida.",
    "Nem todos os amigos são para sempre.",
    "As pessoas mudam, e nem sempre para melhor.",
    "A vida é cheia de incertezas.",
    "Às vezes, a solidão é inevitável.",
    "As decepções são constantes.",
    "O futuro é incerto e assustador.",
    "Às vezes, não há um final feliz.",
    "O medo pode te paralisar.",
    "Nem sempre conseguimos o que queremos.",
    "A dor faz parte da existência.",
    "Os erros do passado podem te assombrar.",
    "Algumas cicatrizes nunca somem.",
    "Nem toda batalha é vencida.",
    "O fracasso pode ser definitivo.",
    "As dificuldades nunca acabam.",
    "Às vezes, não há saída.",
    "Os problemas se acumulam sem aviso.",
    "O mundo pode ser cruel.",
    "Não há garantias na vida.",
    "O sofrimento pode ser longo.",
    "Os sonhos podem ser esmagados pela realidade.",
    "O amor nem sempre dura.",
    "As perdas ensinam, mas deixam marcas.",
    "A esperança pode ser em vão.",
    "A sorte nem sempre está ao nosso lado.",
    "A dor emocional pode ser pior que a física.",
    "Nem sempre há uma lição no sofrimento.",
    "As melhores intenções podem dar errado.",
    "O passado pode ser um fardo pesado.",
    "A ansiedade pode consumir seus dias.",
    "O cansaço pode ser maior que a motivação.",
    "A vida pode se tornar uma rotina vazia.",
    "Alguns erros são irreversíveis.",
    "Nem sempre há uma segunda chance.",
    "Algumas portas se fecham para sempre.",
    "O medo do fracasso pode te impedir de tentar.",
    "A nostalgia pode ser dolorosa.",
    "Os sonhos podem se tornar pesadelos.",
    "A tristeza pode ser silenciosa e persistente.",
    "O tempo pode nos afastar das pessoas que amamos.",
    "A confiança pode ser quebrada em um instante.",
    "Às vezes, não há nada que possamos fazer.",
    "O vazio pode ser avassalador.",
    "O sucesso pode ser solitário.",
    "Nem toda luta vale a pena.",
    "A vida pode ser cansativa.",
    "Às vezes, a escuridão parece interminável.",
    "Algumas batalhas já estão perdidas antes de começarem.",
    "A realidade pode destruir os sonhos mais bonitos.",
    "O caminho pode ser longo e sem recompensas.",
    "As palavras podem ferir mais do que golpes.",
    "O amor pode se transformar em indiferença.",
    "O tempo não volta atrás, não importa o quanto desejemos.",
    "Às vezes, simplesmente não há justiça no mundo.",
    "A vida é feita de escolhas diárias.",
    "O futuro é construído com pequenas ações.",
    "Cada dia traz uma nova oportunidade.",
    "Às vezes, o caminho é mais importante que o destino.",
    "A rotina pode ser tanto um desafio quanto uma oportunidade.",
    "Nada dura para sempre, nem as dificuldades.",
    "O que você faz hoje pode refletir no amanhã.",
    "O equilíbrio entre trabalho e descanso é essencial.",
    "Existem momentos de calma antes da tempestade.",
    "O silêncio pode ser mais revelador do que palavras.",
    "A paciência é necessária em algumas situações.",
    "Às vezes, as coisas simplesmente acontecem.",
    "As escolhas nem sempre são fáceis.",
    "O tempo passa, mas as lembranças ficam.",
    "Nem sempre temos o controle sobre tudo.",
    "A vida oferece oportunidades em diferentes momentos.",
    "É importante saber esperar o momento certo.",
    "Cada um tem seu próprio ritmo.",
    "A vida segue seu curso, independentemente de nossas ações.",
    "O sucesso é uma combinação de esforço e sorte.",
    "Às vezes, os problemas parecem não ter solução.",
    "A visão de mundo pode mudar ao longo do tempo.",
    "A vida é uma sequência de altos e baixos.",
    "Nosso destino está nas nossas mãos, mas também em fatores externos.",
    "A introspecção é uma forma de crescimento.",
    "A vida é um aprendizado constante.",
    "Cada experiência traz uma nova lição.",
    "Não há garantias, mas sempre há chances.",
    "Às vezes, a felicidade está nas pequenas coisas.",
    "A esperança é a última que morre.",
    "É importante ter momentos para si mesmo.",
    "Às vezes, a resposta está em não fazer nada.",
    "A vida é um fluxo constante de mudanças.",
    "Tudo tem sua hora certa.",
    "Nem tudo precisa ser perfeito.",
    "É normal passar por fases difíceis.",
    "A vida é como uma estrada cheia de curvas.",
    "A tranquilidade pode ser encontrada nas coisas simples.",
    "A flexibilidade é uma virtude importante.",
    "Existem diferentes formas de alcançar um objetivo.",
    "O tempo ensina a lidar com as adversidades.",
    "A perseverança é um ponto chave no caminho.",
    "A vida nunca é apenas preto ou branco.",
    "Os dias bons e ruins fazem parte da jornada.",
    "A adaptação é uma habilidade importante.",
    "Às vezes, a vida nos leva por caminhos inesperados.",
    "Não é possível controlar tudo, mas podemos aprender a lidar.",
    "É preciso saber aceitar o que não podemos mudar.",
    "O maior desafio é a capacidade de adaptação.",
    "A confiança é construída ao longo do tempo.",
    "A vida é uma busca constante por equilíbrio.",
    "Cada pessoa tem sua própria jornada.",
    "O tempo traz clareza para muitas situações.",
    "O aprendizado nunca é perdido.",
    "As pequenas vitórias são tão importantes quanto as grandes.",
    "A busca pelo autoconhecimento é constante.",
    "Às vezes, as respostas estão em nos ouvirmos.",
    "A vida é feita de momentos e memórias.",
    "O importante é como reagimos às situações.",
    "A mudança pode ser desconfortável, mas necessária.",
    "As oportunidades aparecem de diversas formas.",
    "É importante saber quando seguir em frente.",
    "Às vezes, é preciso dar um passo atrás para avançar.",
    "A vida é feita de escolhas, cada uma com suas consequências.",
    "Tudo o que acontece tem uma razão, mesmo que não a vejamos imediatamente.",
    "A visão de futuro pode ser moldada pelo presente.",
    "O equilíbrio é uma busca constante.",
    "A mudança começa de dentro para fora.",
    "O aprendizado é mais do que só acumular conhecimento.",
    "O caminho nem sempre é claro, mas é importante seguir.",
    "As coisas podem não acontecer como planejado, e isso está tudo bem.",
    "A vida é uma combinação de esforço, sorte e momentos inesperados.",
    "A persistência, apesar das dificuldades, é essencial.",
    "Nem sempre sabemos qual é o melhor caminho, mas devemos seguir.",
    "A vida é feita de escolhas e cada escolha tem suas consequências.",
    "Às vezes, o melhor é aceitar as coisas como elas são.",
    "Cada experiência deixa uma marca, de algum tipo.",
    "O equilíbrio entre ação e reflexão é fundamental.",
    "As vitórias não são sempre evidentes, mas existem.",
    "A vida segue seu curso, e com ela, seguimos também.",
    "Existem momentos que exigem mais paciência que ação.",
    "Às vezes, o momento certo para agir é aquele em que esperamos.",
    "Não podemos controlar os outros, mas podemos controlar nossas reações.",
    "Cada pessoa é um reflexo de suas próprias experiências.",
    "O caminho até a paz interior pode ser longo e desafiador.",
    "A reflexão sobre as próprias escolhas é uma maneira de evoluir.",
    "Os momentos de pausa também são valiosos para o crescimento.",
    "Às vezes, é preciso passar por dificuldades para aprender algo novo.",
    "A experiência é uma boa professora, embora muitas vezes exigente.",
    "A vida não é uma competição, mas um processo de evolução contínua.",
  ];

  const [frase, setFrase] = useState("");
  const [imagem, setImagem] = useState(fechado);
  const [quebrado, setQuebrado] = useState(false);

  const tocarSom = (som) => {
    const audio = new Audio(som);
    audio.play();
  };

  const pegarFraseAleatoria = () => {
    if (!quebrado) {
      const fraseAleatoria =
        frasesBiscoito[Math.floor(Math.random() * frasesBiscoito.length)];
      setFrase(`"${fraseAleatoria}"`);
      setImagem(aberto);
      setQuebrado(true);
      tocarSom(music);
    }
  };

  const reiniciar = () => {
    setFrase("");
    setImagem(fechado);
    setQuebrado(false);
  };

  return (
    <div className="container">
      <h1>Biscoito da Sorte</h1>
      <h2>幸運餅乾</h2>
      <img
        src={imagem}
        alt="Biscoito da sorte"
        onClick={pegarFraseAleatoria}
        style={{ cursor: !quebrado ? "pointer" : "default" }}
      />
      <h3>{frase}</h3>
      {quebrado && <button onClick={reiniciar}>Pegar mais um?</button>}
    </div>
  );
}

export default App;
